replicaCount: 1

image:
  repository: prom/prometheus
  tag: "v2.27.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 9090

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi

config:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["customer-crud:3000"]
