# version: '3'

# services:
#   jaeger:
#     image: jaegertracing/all-in-one:1.45
#     ports:
#       - "6831:6831/udp"  # Port for receiving traces via UDP (default)
#       - "16686:16686"    # Port for Jaeger UI
#       - "14250:14250"    # Port for receiving traces via OTLP
#       - "4318:4318"    # Port for receiving traces via OTLP HTTP
#     environment:
#       - COLLECTOR_ZIPKIN_HTTP_PORT=9411  # Enable Zipkin format on port 9411
#       - COLLECTOR_OTLP_ENABLED=true
#       - COLLECTOR_OTLP_HTTP_PORT=4318    # Enable OTLP HTTP on port 4318

version: '3'

networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "6001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
  
  customer_curd:
    image: dipeshrijal/customer_curd:v4
    ports:
      - 3000:3000
    networks:
      - monitoring

volumes:
  grafana-storage:
