version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.45
    ports:
      - "6831:6831/udp"  # Port for receiving traces via UDP (default)
      - "16686:16686"    # Port for Jaeger UI
      - "14250:14250"    # Port for receiving traces via OTLP
      - "4318:4318"    # Port for receiving traces via OTLP HTTP
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411  # Enable Zipkin format on port 9411
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_PORT=4318    # Enable OTLP HTTP on port 4318
