replicaCount: 1

image:
  repository: mongodb/mongodb-community-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 27017

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
