replicaCount: 1

image:
  repository: registry
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

resources: {}
