apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jaeger.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "jaeger.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "jaeger.name" . }}
    spec:
      containers:
        - name: {{ include "jaeger.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: jaeger-ui
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .port }}
              protocol: {{ .protocol }}
            {{- end }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
