apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{ include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: {{ .Values.config.global.scrape_interval }}
    scrape_configs:
    {{- range .Values.config.scrape_configs }}
      - job_name: '{{ .job_name }}'
        static_configs:
        {{- range .static_configs }}
          - targets: {{ .targets | toJson }}
        {{- end }}
    {{- end }}
