apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local-registry.fullname" . }}
  labels:
    {{- include "local-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "local-registry.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "local-registry.name" . }}
    spec:
      containers:
        - name: registry
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: {{ include "local-registry.fullname" . }}-pvc
