apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "local-registry.fullname" . }}-pvc
  labels:
    {{- include "local-registry.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | default "standard" }}
